---
name: Barcode Buddy for Grocy
version: 1.2.1
slug: bbuddy-grocy
description: Barcode system for Grocy
url: https://github.com/ljsquare/hassio/barcodebuddy-homeassistant
webui: http://[HOST]:[PORT:80]
panel_icon: mdi:barcode-scan
startup: system
arch:
  - aarch64
  - amd64
  - armv7
  - i386
boot: auto
full_access: true
init: false
map:
  - config:rw
  - ssl
ports:
  80/tcp: 8621
ports_description:
  80/tcp: Web interface
options:
  attach_barcodescanner: false
  device: /dev/input/event0
  curl_allow_insecure_ssl_ca: false
  curl_allow_insecure_ssl_host: false
schema:
  attach_barcodescanner: bool
  device: device(subsystem=input)
  curl_allow_insecure_ssl_ca: bool
  curl_allow_insecure_ssl_host: bool
