#!/usr/bin/bash
# #!/usr/bin/env bashio

#FOLDER=$(bashio::config 'folder')

cd /agent
if [ ! -d "/data/Media" ]
then
  mkdir /data/Media
fi
if [ ! -d "/data/Commands" ]
then
  mkdir /data/Commands
fi

#if [ ! -d "/share/${folder}"]
#then
#  mkdir /share/${folder}
#fi

ln -s /data/Media Media
ln -s /data/Commands Commands
#ln -s /share/${folder} Media/WebServerRoot/Media

./Agent
